# Generated by Django 5.1.11 on 2026-08-19 20:06

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('checked_in_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('access_control', 'Controle de acesso'), ('facial_recognition', 'Reconhecimento facial')], default='manual', max_length=30)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checkins', to='students.student')),
            ],
            options={
                'ordering': ['-checked_in_at', '-created_at'],
                'indexes': [models.Index(fields=['student', 'checked_in_at'], name='checkin_student_date_idx')],
            },
        ),
    ]
