# Generated by Django 5.1.11 on 2026-08-21 12:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0001_initial'),
        ('checkins', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyCheckInGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.DateField(verbose_name='Competência')),
                ('target_count', models.PositiveIntegerField(verbose_name='Meta de check-ins')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='monthly_checkin_goals', to='academy.academy', verbose_name='Academia')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_checkin_goals', to=settings.AUTH_USER_MODEL, verbose_name='Criada por')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='updated_checkin_goals', to=settings.AUTH_USER_MODEL, verbose_name='Atualizada por')),
            ],
            options={
                'verbose_name': 'Meta mensal de check-ins',
                'verbose_name_plural': 'Metas mensais de check-ins',
                'ordering': ['-period'],
                'constraints': [models.UniqueConstraint(fields=('academy', 'period'), name='unique_checkin_goal_per_academy_period'), models.UniqueConstraint(condition=models.Q(('academy__isnull', True)), fields=('period',), name='unique_global_checkin_goal_period'), models.CheckConstraint(condition=models.Q(('target_count__gt', 0)), name='checkin_goal_target_count_positive')],
            },
        ),
    ]
