# Generated by Django 5.1.11 on 2026-08-24 13:04

import django.db.models.deletion
from django.db import migrations, models


def assign_checkin_unit(apps, schema_editor):
    CheckIn = apps.get_model("checkins", "CheckIn")
    for checkin in CheckIn.objects.filter(unit__isnull=True).select_related("student"):
        checkin.unit_id = checkin.student.unit_id
        checkin.save(update_fields=["unit"])


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0002_unit'),
        ('students', '0004_student_academy_student_unit'),
        ('checkins', '0003_checkin_access_result_checkin_block_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkin',
            name='device_response',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='checkin',
            name='location',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='checkin',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='checkins', to='academy.unit'),
        ),
        migrations.RunPython(assign_checkin_unit, migrations.RunPython.noop),
    ]
