# Generated by Django 5.1.11 on 2026-08-24 14:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0003_academyoperationalsettings'),
        ('checkins', '0004_checkin_device_response_checkin_location_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='checkin',
            name='authorized_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='authorized_checkins', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='checkin',
            name='contingency_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name='AccessPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('require_active_enrollment', models.BooleanField(default=True)),
                ('block_defaulting_students', models.BooleanField(default=True)),
                ('allow_manual_contingency', models.BooleanField(default=True)),
                ('instructions', models.CharField(blank=True, max_length=255)),
                ('unit', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='access_policy', to='academy.unit')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
