# Generated by Django 5.1.11 on 2026-08-10 16:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plans', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contracted_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor contratado')),
                ('start_date', models.DateField(verbose_name='Data de início')),
                ('due_date', models.DateField(verbose_name='Data de vencimento')),
                ('status', models.CharField(choices=[('active', 'Ativa'), ('frozen', 'Congelada'), ('canceled', 'Cancelada'), ('finished', 'Encerrada'), ('expired', 'Vencida')], default='active', max_length=20, verbose_name='Status')),
                ('billing_method', models.CharField(choices=[('monthly', 'Mensal'), ('full', 'À vista')], default='monthly', max_length=20, verbose_name='Forma de cobrança')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='plans.plan', verbose_name='Plano')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='students.student', verbose_name='Aluno')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
