# Generated by Django 5.1.11 on 2026-08-10 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0001_initial'),
        ('plans', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['active', 'frozen'])), fields=('student', 'plan'), name='unique_active_plan_per_student'),
        ),
    ]
