# Generated by Django 5.1.11 on 2026-08-10 18:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0002_enrollment_unique_active_plan_per_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnrollmentFreeze',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('frozen_at', models.DateField(verbose_name='Data do congelamento')),
                ('reactivated_at', models.DateField(blank=True, null=True, verbose_name='Data da reativação')),
                ('reason', models.TextField(blank=True, verbose_name='Motivo')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='freezes', to='enrollments.enrollment', verbose_name='Matrícula')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
