# Generated by Django 5.1.11 on 2026-08-10 19:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0003_enrollmentfreeze'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnrollmentHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(choices=[('created', 'Matrícula criada'), ('frozen', 'Matrícula congelada'), ('reactivated', 'Matrícula reativada'), ('canceled', 'Matrícula cancelada'), ('finished', 'Matrícula encerrada')], max_length=20, verbose_name='Tipo do evento')),
                ('event_date', models.DateField(verbose_name='Data do evento')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='enrollments.enrollment', verbose_name='Matrícula')),
            ],
            options={
                'verbose_name': 'Histórico da matrícula',
                'verbose_name_plural': 'Históricos das matrículas',
                'ordering': ['-event_date', '-created_at'],
            },
        ),
    ]
