# Generated by Django 5.1.11 on 2026-08-24 13:04

import django.db.models.deletion
from django.db import migrations, models


def assign_enrollment_unit(apps, schema_editor):
    Enrollment = apps.get_model("enrollments", "Enrollment")
    for enrollment in Enrollment.objects.filter(unit__isnull=True).select_related("student"):
        enrollment.unit_id = enrollment.student.unit_id
        enrollment.save(update_fields=["unit"])


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0002_unit'),
        ('students', '0004_student_academy_student_unit'),
        ('enrollments', '0006_enrollment_commercial_audit'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='academy.unit'),
        ),
        migrations.RunPython(assign_enrollment_unit, migrations.RunPython.noop),
    ]
