# Generated by Django 5.1.11 on 2026-08-24 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0007_enrollment_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='cancellation_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='frozen_until',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='renewed_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='renewals', to='enrollments.enrollment'),
        ),
        migrations.AlterField(
            model_name='enrollmenthistory',
            name='event_type',
            field=models.CharField(choices=[('created', 'Matrícula criada'), ('frozen', 'Matrícula congelada'), ('reactivated', 'Matrícula reativada'), ('canceled', 'Matrícula cancelada'), ('finished', 'Matrícula encerrada'), ('renewed', 'Matrícula renovada')], max_length=20, verbose_name='Tipo do evento'),
        ),
    ]
