# Generated by Django 6.0.7 on 2026-08-03 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_student_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='identifier',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
