# Generated by Django 5.1.11 on 2026-08-21 15:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academy', '0002_unit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('event_type', models.CharField(choices=[('overdue_charge', 'Cobrança vencida'), ('recurring_rejected', 'Recorrência rejeitada'), ('prolonged_absence', 'Ausência prolongada'), ('plan_ending', 'Plano próximo do fim'), ('birthday', 'Aniversário'), ('visit_without_return', 'Visita sem retorno')], max_length=40)),
                ('action_description', models.CharField(max_length=255)),
                ('academy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='automation_rules', to='academy.academy')),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='automation_rules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AutomationExecution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('executed', 'Executada'), ('skipped', 'Ignorada'), ('failed', 'Falhou')], default='executed', max_length=20)),
                ('entity_type', models.CharField(blank=True, max_length=80)),
                ('entity_id', models.CharField(blank=True, max_length=64)),
                ('explanation', models.CharField(max_length=255)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('triggered_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='triggered_automations', to=settings.AUTH_USER_MODEL)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='executions', to='automations.automationrule')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
