# Generated by Django 5.1.11 on 2026-08-24 13:04

import django.db.models.deletion
from django.db import migrations, models


def assign_automation_unit(apps, schema_editor):
    AutomationRule = apps.get_model("automations", "AutomationRule")
    for rule in AutomationRule.objects.filter(unit__isnull=True).select_related("academy"):
        unit = rule.academy.units.filter(active=True).order_by("created_at").first()
        rule.unit_id = unit.pk if unit else None
        rule.save(update_fields=["unit"])


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0002_unit'),
        ('automations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='automationrule',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='automation_rules', to='academy.unit'),
        ),
        migrations.RunPython(assign_automation_unit, migrations.RunPython.noop),
    ]
