# Generated by Django 5.1.11 on 2026-08-21 15:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0002_unit'),
        ('workouts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='exercises', to='academy.unit'),
        ),
        migrations.AddField(
            model_name='workoutplan',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='workout_plans', to='academy.unit'),
        ),
        migrations.AddField(
            model_name='workouttemplate',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='workout_templates', to='academy.unit'),
        ),
        migrations.CreateModel(
            name='WorkoutSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scheduled_for', models.DateField(db_index=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('planned', 'Planejada'), ('completed', 'Realizada'), ('skipped', 'Não realizada')], default='planned', max_length=20)),
                ('duration_minutes', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recorded_workout_sessions', to=settings.AUTH_USER_MODEL)),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='workouts.workoutplan')),
            ],
            options={
                'ordering': ['-scheduled_for', '-created_at'],
                'constraints': [models.UniqueConstraint(fields=('workout', 'scheduled_for'), name='unique_workout_session_date')],
            },
        ),
        migrations.CreateModel(
            name='WorkoutTemplateExercise',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sets', models.PositiveSmallIntegerField(default=3)),
                ('repetitions', models.CharField(default='10', max_length=40)),
                ('load', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('rest_seconds', models.PositiveSmallIntegerField(default=60)),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='template_exercises', to='workouts.exercise')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='template_exercises', to='workouts.workouttemplate')),
            ],
            options={
                'ordering': ['order', 'created_at'],
                'constraints': [models.UniqueConstraint(fields=('template', 'exercise'), name='unique_exercise_per_template')],
            },
        ),
    ]
