# Generated by Django 5.1.11 on 2026-08-27 18:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0002_exercise_unit_workoutplan_unit_workouttemplate_unit_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutLoadRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('load', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('sets', models.PositiveSmallIntegerField()),
                ('repetitions', models.CharField(max_length=40)),
                ('recorded_at', models.DateField(db_index=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='workout_load_records', to=settings.AUTH_USER_MODEL)),
                ('workout_exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='load_history', to='workouts.workoutexercise')),
            ],
            options={
                'ordering': ['-recorded_at', '-created_at'],
            },
        ),
    ]
