# Generated by Django 5.1.11 on 2026-08-07 15:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('search_name', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('cpf', models.CharField(blank=True, max_length=14, null=True, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('identifier', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('cep', models.CharField(blank=True, max_length=9, null=True)),
                ('street', models.CharField(blank=True, max_length=150, null=True)),
                ('number', models.CharField(blank=True, max_length=10, null=True)),
                ('neighborhood', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=2, null=True)),
                ('emergency_contact', models.CharField(blank=True, max_length=100, null=True)),
                ('emergency_phone', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
