# Generated by Django 5.1.11 on 2026-08-24 13:04

import django.db.models.deletion
from django.db import migrations, models


def assign_student_scope(apps, schema_editor):
    Academy = apps.get_model("academy", "Academy")
    Student = apps.get_model("students", "Student")
    academy = Academy.objects.order_by("created_at").first()
    if not academy:
        return
    unit = academy.units.filter(active=True).order_by("created_at").first()
    Student.objects.filter(academy__isnull=True).update(academy=academy, unit=unit)


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0002_unit'),
        ('students', '0003_monthlyactivestudentgoal'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='academy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='students', to='academy.academy'),
        ),
        migrations.AddField(
            model_name='student',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='students', to='academy.unit'),
        ),
        migrations.RunPython(assign_student_scope, migrations.RunPython.noop),
    ]
