# Generated by Django 5.1.11 on 2026-08-24 14:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_student_academy_student_unit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentInteraction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('interaction_type', models.CharField(choices=[('call', 'Ligação'), ('whatsapp', 'WhatsApp'), ('email', 'E-mail'), ('note', 'Observação')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('completed', 'Concluído')], default='pending', max_length=20)),
                ('notes', models.TextField()),
                ('next_action', models.CharField(blank=True, max_length=255)),
                ('next_contact_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_student_interactions', to=settings.AUTH_USER_MODEL)),
                ('responsible', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responsible_student_interactions', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='interactions', to='students.student')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
