# Generated by Django 5.1.11 on 2026-08-24 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_studentinteraction'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='email_opt_in',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='whatsapp_opt_in',
            field=models.BooleanField(default=False),
        ),
    ]
