# Generated by Django 6.0.7 on 2026-08-03 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='academy',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='academy',
            name='cnpj',
            field=models.CharField(blank=True, max_length=18, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='academy',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='academy',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
