# Generated by Django 5.1.11 on 2026-08-24 14:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0002_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademyOperationalSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_grace_days', models.PositiveSmallIntegerField(default=7)),
                ('cancellation_reasons', models.TextField(blank=True)),
                ('access_block_reasons', models.TextField(blank=True)),
                ('opening_hours', models.JSONField(blank=True, default=dict)),
                ('automations_enabled', models.BooleanField(default=True)),
                ('academy', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='operational_settings', to='academy.academy')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
