# Generated by Django 6.0.7 on 2026-08-04 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0002_academy_active_academy_cnpj_academy_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='academy',
            name='trade_name',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
