# Generated by Django 5.1.11 on 2026-08-21 15:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0001_initial'),
        ('users', '0002_alter_user_managers_academyuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdministrativeAudit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(max_length=80)),
                ('entity_type', models.CharField(max_length=80)),
                ('entity_id', models.CharField(blank=True, max_length=64)),
                ('previous_state', models.JSONField(blank=True, default=dict)),
                ('new_state', models.JSONField(blank=True, default=dict)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('origin', models.CharField(default='web', max_length=40)),
                ('academy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='administrative_audits', to='academy.academy')),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='administrative_audits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['academy', '-created_at'], name='users_admin_academy_fbe0d3_idx')],
            },
        ),
    ]
