# Generated by Django 5.1.11 on 2026-08-21 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0002_unit'),
        ('users', '0003_administrativeaudit'),
    ]

    operations = [
        migrations.AddField(
            model_name='academyuser',
            name='active_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_users', to='academy.unit'),
        ),
    ]
