# Generated by Django 5.1.11 on 2026-08-26 12:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0004_academy_onboarding_fields'),
        ('users', '0006_user_is_student_portal_user_two_factor_enabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedReportView',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('period', models.CharField(max_length=7)),
                ('favorite_questions', models.JSONField(blank=True, default=list)),
                ('is_default', models.BooleanField(default=False)),
                ('scope', models.CharField(choices=[('personal', 'Pessoal'), ('unit', 'Unidade'), ('academy', 'Academia')], default='personal', max_length=12)),
                ('academy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_report_views', to='academy.academy')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_report_views', to=settings.AUTH_USER_MODEL)),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='saved_report_views', to='academy.unit')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DashboardPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(blank=True, choices=[('OWNER', 'Proprietário'), ('ADMIN', 'Administrador'), ('MANAGER', 'Gerente'), ('RECEPTION', 'Recepção'), ('TRAINER', 'Professor'), ('FINANCIAL', 'Financeiro')], max_length=20)),
                ('hidden_sections', models.JSONField(blank=True, default=list)),
                ('section_order', models.JSONField(blank=True, default=list)),
                ('academy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_preferences', to='academy.academy')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_preferences', to='academy.unit')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('academy', 'user'), name='unique_user_dashboard_preference'), models.UniqueConstraint(condition=models.Q(('user__isnull', True)), fields=('academy', 'role', 'unit'), name='unique_scope_dashboard_preference')],
            },
        ),
        migrations.CreateModel(
            name='OperationalNotificationState',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notification_key', models.CharField(max_length=80)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_states', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'notification_key'), name='unique_user_notification_state')],
            },
        ),
    ]
