# Generated by Django 5.1.11 on 2026-09-02 17:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0004_academy_onboarding_fields'),
        ('users', '0007_savedreportview_dashboardpreference_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalTerm',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=160)),
                ('content', models.TextField()),
                ('active', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('academy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='legal_terms', to='academy.academy')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_legal_terms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-version'],
            },
        ),
        migrations.CreateModel(
            name='LegalTermAcceptance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accepted_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='acceptances', to='users.legalterm')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='legal_term_acceptances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-accepted_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='legalterm',
            constraint=models.UniqueConstraint(fields=('academy', 'version'), name='unique_legal_term_version_per_academy'),
        ),
        migrations.AddConstraint(
            model_name='legaltermacceptance',
            constraint=models.UniqueConstraint(fields=('term', 'user'), name='unique_legal_term_acceptance'),
        ),
    ]
