# Generated by Django 5.1.11 on 2026-08-24 13:04

import django.db.models.deletion
from django.db import migrations, models


def assign_plan_academy(apps, schema_editor):
    Academy = apps.get_model("academy", "Academy")
    Plan = apps.get_model("plans", "Plan")
    academy = Academy.objects.order_by("created_at").first()
    if academy:
        Plan.objects.filter(academy__isnull=True).update(academy=academy)


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0002_unit'),
        ('plans', '0003_plan_contract_rules'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='academy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='plans', to='academy.academy'),
        ),
        migrations.RunPython(assign_plan_academy, migrations.RunPython.noop),
    ]
