# Generated by Django 5.1.11 on 2026-08-26 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0004_academy_onboarding_fields'),
        ('plans', '0005_plan_installment_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='available_units',
            field=models.ManyToManyField(blank=True, related_name='available_plans', to='academy.unit', verbose_name='Unidades disponíveis'),
        ),
        migrations.AddField(
            model_name='plan',
            name='cancellation_penalty_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Multa de cancelamento (%)'),
        ),
        migrations.AddField(
            model_name='plan',
            name='grace_period_days',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Carência (dias)'),
        ),
        migrations.AddField(
            model_name='plan',
            name='promotion_ends_at',
            field=models.DateField(blank=True, null=True, verbose_name='Fim da promoção'),
        ),
        migrations.AddField(
            model_name='plan',
            name='promotion_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor promocional'),
        ),
    ]
