# Generated by Django 5.1.11 on 2026-08-21 14:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0003_monthlyactivestudentgoal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=150)),
                ('event_type', models.CharField(choices=[('class', 'Aula'), ('assessment', 'Avaliação'), ('task', 'Tarefa'), ('contact', 'Contato'), ('visit', 'Visita')], max_length=20)),
                ('status', models.CharField(choices=[('scheduled', 'Agendado'), ('in_progress', 'Em andamento'), ('completed', 'Realizado'), ('canceled', 'Cancelado')], default='scheduled', max_length=20)),
                ('starts_at', models.DateTimeField(db_index=True)),
                ('ends_at', models.DateTimeField()),
                ('location', models.CharField(blank=True, max_length=120)),
                ('notes', models.TextField(blank=True)),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedule_events', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='schedule_events', to='students.student')),
            ],
            options={
                'ordering': ['starts_at', 'created_at'],
            },
        ),
    ]
