# Generated by Django 5.1.11 on 2026-08-24 13:04

import django.db.models.deletion
from django.db import migrations, models


def assign_schedule_unit(apps, schema_editor):
    ScheduleEvent = apps.get_model("schedule", "ScheduleEvent")
    Unit = apps.get_model("academy", "Unit")
    fallback = Unit.objects.filter(active=True).order_by("created_at").first()
    for event in ScheduleEvent.objects.filter(unit__isnull=True).select_related("student"):
        event.unit_id = event.student.unit_id if event.student_id else (fallback.pk if fallback else None)
        event.save(update_fields=["unit"])


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0002_unit'),
        ('students', '0004_student_academy_student_unit'),
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleevent',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='schedule_events', to='academy.unit'),
        ),
        migrations.RunPython(assign_schedule_unit, migrations.RunPython.noop),
    ]
