# Generated by Django 5.1.11 on 2026-08-24 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_scheduleevent_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleevent',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scheduleevent',
            name='reminder_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
