import { useCallback, useEffect, useState, type FormEvent } from "react";
import toast from "react-hot-toast";
import DashboardLayout from "@/layouts/DashboardLayout";
import PageHeader from "@/components/PageHeader";
import { Api } from "@/services/http";

type Student={id:string;name:string;email:string|null}; type Document={id:string;student_name:string;title:string;document_type:string;version:number;expires_at:string|null;accepted_at:string|null};
const unwrap=<T,>(data:T[]|{results:T[]})=>Array.isArray(data)?data:data.results;
export default function Documents(){const[students,setStudents]=useState<Student[]>([]);const[documents,setDocuments]=useState<Document[]>([]);const[selected,setSelected]=useState("");const load=useCallback(async()=>{const[s,d]=await Promise.all([Api.get("/students/"),Api.get("/operations/documents/")]);setStudents(unwrap(s.data));setDocuments(unwrap(d.data));},[]);useEffect(()=>{load().catch(()=>toast.error("Não foi possível carregar os documentos."));},[load]);
 async function create(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=new FormData(e.currentTarget);await Api.post("/operations/documents/",Object.fromEntries(form));e.currentTarget.reset();toast.success("Documento registrado e disponibilizado no portal.");await load();}
 async function createPortal(){const student=students.find(x=>x.id===selected);if(!student)return;const email=prompt("E-mail de acesso:",student.email||"");const password=prompt("Senha inicial com ao menos 8 caracteres:");if(!email||!password)return;await Api.post(`/users/portal/students/${student.id}/access/`,{email,password});toast.success("Acesso do portal criado.");}
 const input="h-11 rounded-xl border border-slate-200 px-3 text-sm";return <DashboardLayout><PageHeader title="Documentos e portal" subtitle="Contratos, autorizações, validade, aceite digital e acesso do aluno."/><section className="rounded-2xl border bg-white p-6"><form onSubmit={create} className="grid gap-3 md:grid-cols-2"><select required name="student" value={selected} onChange={e=>setSelected(e.target.value)} className={input}><option value="">Selecione o aluno</option>{students.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select><select name="document_type" className={input}><option value="contract">Contrato</option><option value="medical">Atestado</option><option value="authorization">Autorização</option><option value="other">Outro</option></select><input required name="title" placeholder="Título do documento" className={input}/><input name="expires_at" type="date" className={input}/><textarea name="content_snapshot" placeholder="Conteúdo ou termos apresentados ao aluno" className="min-h-28 rounded-xl border p-3 md:col-span-2"/><button className="h-11 rounded-xl bg-blue-600 font-bold text-white">Criar documento</button><button type="button" disabled={!selected} onClick={createPortal} className="h-11 rounded-xl border font-bold text-blue-700 disabled:opacity-40">Criar/redefinir acesso ao portal</button></form></section><section className="mt-5 rounded-2xl border bg-white p-6"><h2 className="font-black">Documentos emitidos</h2><div className="mt-4 divide-y">{documents.map(x=><div key={x.id} className="flex flex-wrap justify-between gap-3 py-3 text-sm"><span><strong>{x.title}</strong> · {x.student_name} · versão {x.version}</span><span className={x.accepted_at?"font-bold text-emerald-700":"font-bold text-amber-700"}>{x.accepted_at?"Aceito":"Aguardando aceite"}{x.expires_at?` · vence ${new Date(`${x.expires_at}T12:00:00`).toLocaleDateString("pt-BR")}`:""}</span></div>)}</div>{documents.length===0&&<p className="mt-4 text-sm text-slate-500">Nenhum documento emitido.</p>}</section></DashboardLayout>}
