import { useCallback, useEffect, useState, type FormEvent } from "react";
import toast from "react-hot-toast";
import PageHeader from "@/components/PageHeader";
import DashboardLayout from "@/layouts/DashboardLayout";
import { Api } from "@/services/http";

type Lead = { id: string; name: string; source: string; stage: string; next_action_at: string | null; converted_student: string | null };
type Booking = { id: string; student_name: string; status: string };
type GroupClass = { id: string; title: string; starts_at: string; capacity: number; confirmed_count: number; waitlist_count: number; canceled: boolean; bookings: Booking[] };
type Summary = { total: number; conversion_rate: number; stages: Record<string, number> };
const unwrap = <T,>(value: T[] | { results: T[] }) => Array.isArray(value) ? value : value.results;
const stages = [["new","Novo"],["contacted","Contatado"],["visit","Visita"],["proposal","Proposta"],["won","Convertido"],["lost","Perdido"]];
const field = "h-10 rounded-xl border border-slate-200 bg-white px-3 text-sm outline-none focus:border-blue-400";

export default function Growth() {
    const [leads,setLeads]=useState<Lead[]>([]); const [classes,setClasses]=useState<GroupClass[]>([]); const [summary,setSummary]=useState<Summary>({total:0,conversion_rate:0,stages:{}}); const [loading,setLoading]=useState(true);
    const load=useCallback(async()=>{setLoading(true);try{const [a,b,c]=await Promise.all([Api.get("/operations/leads/"),Api.get("/operations/classes/"),Api.get("/operations/leads/summary/")]);setLeads(unwrap(a.data));setClasses(unwrap(b.data));setSummary(c.data);}catch{toast.error("Não foi possível carregar o módulo comercial.");}finally{setLoading(false);}},[]);
    useEffect(()=>{void load();},[load]);
    async function createLead(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget);await Api.post("/operations/leads/",Object.fromEntries(form));event.currentTarget.reset();toast.success("Lead cadastrado.");await load();}
    async function updateLead(id:string,stage:string){const body:Record<string,string>={stage};if(stage==="lost")body.loss_reason=prompt("Motivo da perda:")||"Não informado";await Api.patch(`/operations/leads/${id}/`,body);await load();}
    async function convert(id:string){const cpf=prompt("CPF do novo aluno:");if(!cpf)return;await Api.post(`/operations/leads/${id}/convert/`,{cpf});toast.success("Lead convertido em aluno.");await load();}
    async function createClass(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget);await Api.post("/operations/classes/",{...Object.fromEntries(form),starts_at:new Date(String(form.get("starts_at"))).toISOString(),ends_at:new Date(String(form.get("ends_at"))).toISOString(),capacity:Number(form.get("capacity"))});event.currentTarget.reset();toast.success("Turma criada.");await load();}
    async function book(id:string){const student=prompt("ID do aluno:");if(!student)return;const response=await Api.post(`/operations/classes/${id}/book/`,{student});toast.success(response.data.status==="waitlist"?"Aluno incluído na lista de espera.":"Inscrição confirmada.");await load();}
    async function mark(classId:string,bookingId:string,status:string){await Api.patch(`/operations/classes/${classId}/bookings/${bookingId}/`,{status});await load();}
    async function cancelClass(id:string){if(!confirm("Cancelar esta turma e todas as reservas?"))return;await Api.post(`/operations/classes/${id}/cancel/`);toast.success("Turma cancelada.");await load();}
    return <DashboardLayout><div className="space-y-6"><PageHeader title="Comercial e turmas" subtitle="Oportunidades, conversão, lotação e presença em um único fluxo." eyebrow="Crescimento da operação" context="Aquisição, conversão e ocupação" />
      <div className="grid gap-3 sm:grid-cols-4">{[["Leads",summary.total],["Conversão",`${summary.conversion_rate}%`],["Visitas",summary.stages.visit||0],["Propostas",summary.stages.proposal||0]].map(([label,value])=><div key={label} className="rounded-2xl border bg-white p-4"><p className="text-xs font-bold uppercase text-slate-400">{label}</p><p className="mt-1 text-2xl font-black">{value}</p></div>)}</div>
      <div className="grid gap-6 xl:grid-cols-2"><section className="rounded-3xl border bg-white p-6"><h2 className="text-xl font-black">Funil de leads</h2><form onSubmit={createLead} className="mt-4 grid gap-3 sm:grid-cols-2"><input required name="name" placeholder="Nome" className={field}/><input name="phone" placeholder="Telefone" className={field}/><input name="email" type="email" placeholder="E-mail" className={field}/><input name="source" placeholder="Origem" className={field}/><input name="next_action_at" type="datetime-local" className={field}/><button className="rounded-xl bg-blue-600 px-4 py-2 font-bold text-white">Cadastrar lead</button></form><div className="mt-5 space-y-2">{loading?<p className="text-sm text-slate-400">Carregando...</p>:leads.length===0?<p className="text-sm text-slate-400">Cadastre a primeira oportunidade comercial.</p>:leads.map(x=><div key={x.id} className="rounded-xl bg-slate-50 p-3 text-sm"><div className="flex flex-wrap items-center justify-between gap-2"><span><strong>{x.name}</strong> · {x.source||"Sem origem"}</span><div className="flex gap-2"><select value={x.stage} onChange={e=>updateLead(x.id,e.target.value)} className="rounded-lg border px-2 py-1">{stages.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select>{!x.converted_student&&<button onClick={()=>convert(x.id)} className="font-bold text-blue-600">Converter</button>}</div></div>{x.next_action_at&&<p className="mt-1 text-slate-500">Próxima ação: {new Date(x.next_action_at).toLocaleString("pt-BR")}</p>}</div>)}</div></section>
      <section className="rounded-3xl border bg-white p-6"><h2 className="text-xl font-black">Aulas coletivas</h2><form onSubmit={createClass} className="mt-4 grid gap-3 sm:grid-cols-2"><input required name="title" placeholder="Nome da turma" className={field}/><input required name="modality" placeholder="Modalidade" className={field}/><input required name="starts_at" type="datetime-local" className={field}/><input required name="ends_at" type="datetime-local" className={field}/><input required name="capacity" type="number" min="1" defaultValue="10" className={field}/><input name="location" placeholder="Local" className={field}/><button className="rounded-xl bg-blue-600 px-4 py-2 font-bold text-white sm:col-span-2">Criar turma</button></form><div className="mt-5 space-y-3">{classes.map(x=><div key={x.id} className={`rounded-xl p-3 text-sm ${x.canceled?"bg-red-50 opacity-70":"bg-slate-50"}`}><div className="flex flex-wrap justify-between gap-2"><span><strong>{x.title}</strong> · {new Date(x.starts_at).toLocaleString("pt-BR")}</span><span>{x.confirmed_count}/{x.capacity} · espera {x.waitlist_count}</span></div><div className="mt-2 flex gap-3"><button disabled={x.canceled} onClick={()=>book(x.id)} className="font-bold text-blue-600 disabled:text-slate-400">Inscrever</button><button disabled={x.canceled} onClick={()=>cancelClass(x.id)} className="font-bold text-red-600 disabled:hidden">Cancelar turma</button></div>{x.bookings.map(b=><div key={b.id} className="mt-2 flex items-center justify-between border-t pt-2"><span>{b.student_name} · {b.status}</span>{["confirmed","waitlist"].includes(b.status)&&<span className="flex gap-2"><button onClick={()=>mark(x.id,b.id,"attended")} className="font-bold text-emerald-700">Presente</button><button onClick={()=>mark(x.id,b.id,"canceled")} className="font-bold text-red-600">Cancelar</button></span>}</div>)}</div>)}</div></section></div>
    </div></DashboardLayout>;
}
