import { useCallback, useEffect, useState, type ReactNode } from "react";
import { LogOut } from "lucide-react";
import toast from "react-hot-toast";
import { Api } from "@/services/http";
import { clearTokens } from "@/features/auth/services/token.service";

type PortalData={student:{name:string;email?:string;phone?:string};enrollments:Array<{id:string;plan:string;status:string}>;charges:Array<{id:string;description:string;due_date:string;status:string}>;checkins:Array<{id:string;checked_in_at:string}>;documents:Array<{id:string;title:string;accepted_at:string|null;expires_at:string|null}>;classes:Array<{id:string;title:string;starts_at:string;location:string;capacity:number;confirmed_count:number;my_booking:{id:string;status:string}|null}>;workouts:Array<{id:string;name:string;objective:string;review_date:string|null;adherence_percentage:number|null;exercises:Array<{name:string;sets:number;repetitions:string;load:string|null}>}>};

export default function Portal(){const[data,setData]=useState<PortalData|null>(null);const[error,setError]=useState("");const load=useCallback(()=>Api.get<PortalData>("/users/portal/me/").then(r=>setData(r.data)).catch(()=>setError("Não foi possível carregar o portal.")),[]);useEffect(()=>{void load();},[load]);
 async function operate(body:Record<string,string>){await Api.post("/users/portal/me/",body);toast.success("Operação concluída.");await load();}
 async function updatePhone(){const phone=prompt("Novo telefone:",data?.student.phone||"");if(phone===null)return;await Api.patch("/users/portal/me/",{phone});toast.success("Telefone atualizado.");await load();}
 if(error)return <main className="p-10 text-red-700">{error}</main>;if(!data)return <main className="p-10 text-slate-500">Carregando seu portal...</main>;
 return <main className="min-h-screen bg-[#f4f7fb] p-5 md:p-10"><div className="mx-auto max-w-6xl"><header className="mb-8 flex flex-wrap items-center justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-blue-600">Portal do aluno</p><h1 className="mt-2 text-3xl font-black text-slate-950">Olá, {data.student.name}</h1><button onClick={updatePhone} className="mt-2 text-sm font-bold text-blue-600">Atualizar telefone</button></div><button onClick={()=>{clearTokens();location.href="/";}} className="flex items-center gap-2 rounded-xl border bg-white px-4 py-2 text-sm font-bold"><LogOut size={16}/> Sair</button></header>
 <div className="grid gap-5 md:grid-cols-2"><Card title="Meus planos">{data.enrollments.map(x=><Row key={x.id}>{x.plan} · {x.status}</Row>)}</Card><Card title="Próximas turmas">{data.classes.map(x=><Row key={x.id}><div><strong>{x.title}</strong><p>{new Date(x.starts_at).toLocaleString("pt-BR")} · {x.location||"Local a definir"} · {x.confirmed_count}/{x.capacity}</p></div>{x.my_booking?<button onClick={()=>operate({operation:"cancel_booking",booking_id:x.my_booking!.id})} className="font-bold text-red-600">Cancelar ({x.my_booking.status})</button>:<button onClick={()=>operate({operation:"book_class",class_id:x.id})} className="font-bold text-blue-600">Reservar</button>}</Row>)}</Card>
 <Card title="Meu treino">{data.workouts.map(x=><Row key={x.id}><div><strong>{x.name}</strong><p>{x.objective} · aderência {x.adherence_percentage??"—"}%</p><ul className="mt-2 text-xs">{x.exercises.map(e=><li key={e.name}>{e.name}: {e.sets} × {e.repetitions}{e.load?` · ${e.load} kg`:""}</li>)}</ul></div></Row>)}</Card><Card title="Financeiro">{data.charges.map(x=><Row key={x.id}>{x.description} · {new Date(`${x.due_date}T12:00:00`).toLocaleDateString("pt-BR")} · {x.status}</Row>)}</Card>
 <Card title="Check-ins recentes">{data.checkins.map(x=><Row key={x.id}>{new Date(x.checked_in_at).toLocaleString("pt-BR")}</Row>)}</Card><Card title="Documentos">{data.documents.map(x=><Row key={x.id}><span>{x.title} · {x.accepted_at?"aceito":"aguardando aceite"}</span>{!x.accepted_at&&<button onClick={()=>operate({operation:"accept_document",document_id:x.id})} className="font-bold text-blue-600">Aceitar</button>}</Row>)}</Card></div>
 </div></main>}

function Card({title,children}:{title:string;children:ReactNode}){return <section className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><h2 className="text-lg font-black text-slate-900">{title}</h2><div className="mt-4 space-y-2">{children||<p className="text-sm text-slate-400">Nenhum registro disponível.</p>}</div></section>}
function Row({children}:{children:ReactNode}){return <div className="flex items-center justify-between gap-3 rounded-xl bg-slate-50 px-4 py-3 text-sm text-slate-700">{children}</div>}
