# Generated by Django 5.1.11 on 2026-08-24 13:04

import django.db.models.deletion
from django.db import migrations, models


def assign_financial_unit(apps, schema_editor):
    Charge = apps.get_model("financial", "Charge")
    CashTransaction = apps.get_model("financial", "CashTransaction")
    for charge in Charge.objects.filter(unit__isnull=True).select_related("enrollment"):
        charge.unit_id = charge.enrollment.unit_id
        charge.save(update_fields=["unit"])
    for transaction in CashTransaction.objects.filter(unit__isnull=True).select_related("charge"):
        transaction.unit_id = transaction.charge.unit_id if transaction.charge_id else None
        transaction.save(update_fields=["unit"])


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0002_unit'),
        ('enrollments', '0007_enrollment_unit'),
        ('financial', '0008_monthlyrevenuegoal'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashtransaction',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cash_transactions', to='academy.unit'),
        ),
        migrations.AddField(
            model_name='charge',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='charges', to='academy.unit'),
        ),
        migrations.RunPython(assign_financial_unit, migrations.RunPython.noop),
    ]
