# Generated by Django 5.1.11 on 2026-08-24 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0009_cashtransaction_unit_charge_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='charge',
            name='payment_provider',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='charge',
            name='payment_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='charge',
            name='pix_code',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='charge',
            name='provider_charge_id',
            field=models.CharField(blank=True, db_index=True, max_length=120),
        ),
        migrations.CreateModel(
            name='PaymentWebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=120, unique=True)),
                ('provider', models.CharField(max_length=40)),
                ('event_type', models.CharField(max_length=40)),
                ('payload', models.JSONField(default=dict)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('charge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='provider_events', to='financial.charge')),
            ],
            options={
                'ordering': ['-processed_at'],
            },
        ),
    ]
