# Generated by Django 5.1.11 on 2026-08-24 15:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academy', '0003_academyoperationalsettings'),
        ('students', '0005_studentinteraction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunicationCampaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('channel', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('email', 'E-mail')], max_length=20)),
                ('segment', models.CharField(choices=[('at_risk', 'Em risco'), ('defaulting', 'Inadimplentes'), ('inactive', 'Inativos'), ('all_active', 'Todos ativos')], max_length=30)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('ready', 'Pronta para integração')], default='draft', max_length=20)),
                ('academy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='communication_campaigns', to='academy.academy')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_campaigns', to=settings.AUTH_USER_MODEL)),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='communication_campaigns', to='academy.unit')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PhysicalAssessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessed_at', models.DateField()),
                ('next_assessment_at', models.DateField(blank=True, null=True)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('height_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('body_fat_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('goal', models.CharField(blank=True, max_length=160)),
                ('notes', models.TextField(blank=True)),
                ('evaluator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='physical_assessments', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='physical_assessments', to='students.student')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='physical_assessments', to='academy.unit')),
            ],
            options={
                'ordering': ['-assessed_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AccessDevice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('identifier', models.CharField(max_length=80)),
                ('kind', models.CharField(choices=[('turnstile', 'Catraca'), ('reader', 'Leitor'), ('facial', 'Reconhecimento facial'), ('simulator', 'Simulador')], default='simulator', max_length=20)),
                ('active', models.BooleanField(default=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('academy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='access_devices', to='academy.academy')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='access_devices', to='academy.unit')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('academy', 'identifier'), name='unique_device_identifier_per_academy')],
            },
        ),
        migrations.CreateModel(
            name='OnboardingProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('step', models.CharField(max_length=80)),
                ('completed', models.BooleanField(default=False)),
                ('academy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='onboarding_progress', to='academy.academy')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='onboarding_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('academy', 'user', 'step'), name='unique_onboarding_step')],
            },
        ),
    ]
