# Generated by Django 5.1.11 on 2026-08-24 16:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
        ('students', '0006_student_email_opt_in_student_whatsapp_opt_in'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessdevice',
            name='credential_env_key',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='accessdevice',
            name='last_error',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='accessdevice',
            name='provider',
            field=models.CharField(default='simulator', max_length=40),
        ),
        migrations.AddField(
            model_name='accessdevice',
            name='status',
            field=models.CharField(choices=[('never_connected', 'Nunca conectado'), ('online', 'Online'), ('offline', 'Offline'), ('error', 'Com falha')], default='never_connected', max_length=20),
        ),
        migrations.AddField(
            model_name='physicalassessment',
            name='blood_pressure',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='physicalassessment',
            name='measurements',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='physicalassessment',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='assessments/photos/'),
        ),
        migrations.AddField(
            model_name='physicalassessment',
            name='resting_heart_rate',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='communicationcampaign',
            name='status',
            field=models.CharField(choices=[('draft', 'Rascunho'), ('ready', 'Pronta para integração'), ('processing', 'Processando'), ('completed', 'Concluída')], default='draft', max_length=20),
        ),
        migrations.CreateModel(
            name='DeviceEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(choices=[('heartbeat', 'Heartbeat'), ('access', 'Acesso'), ('error', 'Erro')], max_length=30)),
                ('success', models.BooleanField(default=True)),
                ('message', models.CharField(blank=True, max_length=255)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='operations.accessdevice')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MessageDelivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recipient', models.CharField(max_length=255)),
                ('provider', models.CharField(default='sandbox', max_length=40)),
                ('status', models.CharField(choices=[('queued', 'Na fila'), ('sent', 'Enviada'), ('failed', 'Falhou'), ('skipped', 'Ignorada')], default='queued', max_length=20)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('last_error', models.CharField(blank=True, max_length=255)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to='operations.communicationcampaign')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='message_deliveries', to='students.student')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('campaign', 'student'), name='unique_campaign_student_delivery')],
            },
        ),
    ]
