# Generated by Django 5.1.11 on 2026-08-24 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0003_accessdevice_webhook_key_hash_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='communicationcampaign',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='communicationcampaign',
            name='template_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='messagedelivery',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='messagedelivery',
            name='external_id',
            field=models.CharField(blank=True, db_index=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='messagedelivery',
            name='status',
            field=models.CharField(choices=[('queued', 'Na fila'), ('sent', 'Enviada'), ('delivered', 'Entregue'), ('failed', 'Falhou'), ('skipped', 'Ignorada')], default='queued', max_length=20),
        ),
    ]
