# Generated by Django 5.1.11 on 2026-08-24 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0004_communicationcampaign_scheduled_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginsession',
            name='refresh_jti',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
    ]
