import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [("operations", "0008_groupclass_schedule_integration"), migrations.swappable_dependency(settings.AUTH_USER_MODEL)]
    operations = [
        migrations.CreateModel(name="OperationalIssue", fields=[("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)), ("created_at", models.DateTimeField(auto_now_add=True)), ("updated_at", models.DateTimeField(auto_now=True)), ("source", models.CharField(db_index=True, max_length=30)), ("source_key", models.CharField(max_length=160)), ("source_url", models.CharField(blank=True, max_length=255)), ("title", models.CharField(max_length=180)), ("detail", models.CharField(blank=True, max_length=255)), ("next_action", models.CharField(max_length=180)), ("priority", models.CharField(choices=[("critical", "Crítica"), ("high", "Alta"), ("medium", "Média"), ("low", "Baixa")], db_index=True, default="medium", max_length=20)), ("status", models.CharField(choices=[("open", "Aberta"), ("in_progress", "Em andamento"), ("resolved", "Resolvida"), ("dismissed", "Descartada")], db_index=True, default="open", max_length=20)), ("due_at", models.DateTimeField(blank=True, db_index=True, null=True)), ("resolved_at", models.DateTimeField(blank=True, null=True)), ("resolution", models.TextField(blank=True)), ("last_synced_at", models.DateTimeField(auto_now=True)), ("academy", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="operational_issues", to="academy.academy")), ("assigned_to", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="assigned_operational_issues", to=settings.AUTH_USER_MODEL)), ("unit", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="operational_issues", to="academy.unit"))], options={"ordering": ["-priority", "due_at", "-created_at"]}),
        migrations.CreateModel(name="OperationalIssueHistory", fields=[("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)), ("created_at", models.DateTimeField(auto_now_add=True)), ("updated_at", models.DateTimeField(auto_now=True)), ("event", models.CharField(max_length=40)), ("message", models.CharField(blank=True, max_length=255)), ("previous_state", models.JSONField(blank=True, default=dict)), ("new_state", models.JSONField(blank=True, default=dict)), ("actor", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="operational_issue_history", to=settings.AUTH_USER_MODEL)), ("issue", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="history", to="operations.operationalissue"))], options={"ordering": ["created_at"]}),
        migrations.AddField(model_name="operationalissue", name="active", field=models.BooleanField(default=True)),
        migrations.AddField(model_name="operationalissuehistory", name="active", field=models.BooleanField(default=True)),
        migrations.AddConstraint(model_name="operationalissue", constraint=models.UniqueConstraint(fields=("academy", "source", "source_key"), name="unique_operational_issue_source")),
    ]
