# Generated by Django 5.1.11 on 2026-08-26 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0009_operationalissue_operationalissuehistory'),
        ('workouts', '0002_exercise_unit_workoutplan_unit_workouttemplate_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='physicalassessment',
            name='workout_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='physical_assessments', to='workouts.workoutplan'),
        ),
    ]
