# Generated by Django 5.1.11 on 2026-08-27 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0011_leadinteraction_leadproposal_campaignsegment'),
    ]

    operations = [
        migrations.AddField(
            model_name='communicationcampaign',
            name='segment_definition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='campaigns', to='operations.campaignsegment'),
        ),
    ]
