# Generated by Django 5.1.11 on 2026-08-27 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0012_communicationcampaign_segment_definition'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdocument',
            name='archived_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='studentdocument',
            name='requires_acceptance',
            field=models.BooleanField(default=True),
        ),
    ]
