# Generated by Django 5.1.11 on 2026-08-27 19:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0008_enrollment_cancellation_reason_and_more'),
        ('operations', '0013_studentdocument_archived_at_and_more'),
        ('students', '0007_student_portal_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='studentdocument',
            constraint=models.UniqueConstraint(fields=('student', 'title', 'version'), name='unique_student_document_title_version'),
        ),
    ]
