# Generated by Django 5.1.11 on 2026-09-02 14:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


def classify_existing_devices(apps, schema_editor):
    AccessDevice = apps.get_model("operations", "AccessDevice")
    AccessDevice.objects.filter(provider="simulator").update(connection_mode="simulator")


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0004_academy_onboarding_fields'),
        ('operations', '0014_studentdocument_unique_student_document_title_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessdevice',
            name='connection_mode',
            field=models.CharField(choices=[('local_connector', 'Conector local'), ('direct_cloud', 'Direta com o Cfit'), ('simulator', 'Simulação')], default='local_connector', max_length=24),
        ),
        migrations.AddField(
            model_name='accessdevice',
            name='local_address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='accessdevice',
            name='local_port',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accessdevice',
            name='model_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name='AccessConnector',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('identifier', models.CharField(max_length=80)),
                ('active', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('never_connected', 'Nunca conectado'), ('online', 'Online'), ('offline', 'Offline'), ('error', 'Com falha')], default='never_connected', max_length=20)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('version', models.CharField(blank=True, max_length=40)),
                ('last_error', models.CharField(blank=True, max_length=255)),
                ('webhook_key_hash', models.CharField(blank=True, max_length=128)),
                ('academy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='access_connectors', to='academy.academy')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='access_connectors', to='academy.unit')),
            ],
        ),
        migrations.AddField(
            model_name='accessdevice',
            name='connector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='devices', to='operations.accessconnector'),
        ),
        migrations.AddConstraint(
            model_name='accessconnector',
            constraint=models.UniqueConstraint(fields=('academy', 'identifier'), name='unique_connector_identifier_per_academy'),
        ),
        migrations.RunPython(classify_existing_devices, migrations.RunPython.noop),
    ]
