import { useCallback, useEffect, useState } from "react";
import { Scale } from "lucide-react";
import { Api } from "@/services/http";
import { EmptyState, ErrorState, LoadingState } from "@/components/AsyncState";

type Assessment = { id: string; assessed_at: string; next_assessment_at: string | null; weight_kg: string | null; height_cm: string | null; body_fat_percentage: string | null; blood_pressure: string; resting_heart_rate: number | null; goal: string; measurements: Record<string,string|number>; evaluator_name: string };

export default function StudentAssessments({ studentId }: { studentId: string }) {
    const [items, setItems] = useState<Assessment[]>([]); const [change, setChange] = useState<{weight_kg:number;body_fat_percentage:number}|null>(null); const [loading,setLoading]=useState(true); const [error,setError]=useState(false);
    const load=useCallback(async()=>{try{setLoading(true);setError(false);const response=await Api.get("/operations/assessments/comparison/",{params:{student:studentId}});setItems(response.data.history);setChange(response.data.change);}catch{setError(true);}finally{setLoading(false);}},[studentId]);
    useEffect(()=>{void load();},[load]);
    if(loading)return <LoadingState label="Carregando avaliações..."/>; if(error)return <ErrorState onRetry={load}/>; if(!items.length)return <EmptyState label="Nenhuma avaliação física" detail="Registre a primeira avaliação pela Central operacional."/>;
    const maxWeight=Math.max(...items.map(item=>Number(item.weight_kg||0)),1);
    return <section className="rounded-2xl border bg-white p-6 shadow-sm"><div className="flex items-center gap-3"><Scale className="text-blue-600"/><div><h2 className="font-black">Evolução física</h2><p className="text-sm text-slate-500">Histórico persistido e comparação entre avaliações.</p></div></div>{change&&<div className="mt-5 grid gap-3 sm:grid-cols-2"><div className="rounded-xl bg-blue-50 p-4 text-sm">Variação de peso <strong className="float-right">{change.weight_kg>0?"+":""}{change.weight_kg.toFixed(2)} kg</strong></div><div className="rounded-xl bg-cyan-50 p-4 text-sm">Variação de gordura <strong className="float-right">{change.body_fat_percentage>0?"+":""}{change.body_fat_percentage.toFixed(2)} p.p.</strong></div></div>}<div className="mt-5 space-y-4">{items.map(item=><article key={item.id} className="rounded-xl border p-4"><div className="flex justify-between text-sm"><strong>{new Date(`${item.assessed_at}T12:00:00`).toLocaleDateString("pt-BR")}</strong><span className="text-slate-500">{item.evaluator_name}</span></div><div className="mt-3 h-2 rounded-full bg-slate-100"><div className="h-2 rounded-full bg-gradient-to-r from-blue-600 to-cyan-400" style={{width:`${Number(item.weight_kg||0)/maxWeight*100}%`}}/></div><p className="mt-3 text-sm text-slate-600">{item.weight_kg||"—"} kg · {item.body_fat_percentage||"—"}% gordura · {item.blood_pressure||"pressão não informada"}</p><p className="mt-1 text-xs text-slate-500">Objetivo: {item.goal||"não informado"}{item.next_assessment_at?` · Próxima: ${new Date(`${item.next_assessment_at}T12:00:00`).toLocaleDateString("pt-BR")}`:""}</p></article>)}</div></section>;
}
