import { useCallback, useEffect, useMemo, useState, type FormEvent } from "react";
import { Plus, Scale } from "lucide-react";
import toast from "react-hot-toast";
import { EmptyState, ErrorState, LoadingState } from "@/components/AsyncState";
import Modal from "@/components/Modal";
import { Api } from "@/services/http";

type Assessment={id:string;assessed_at:string;next_assessment_at:string|null;weight_kg:string|null;height_cm:string|null;body_fat_percentage:string|null;blood_pressure:string;resting_heart_rate:number|null;goal:string;notes:string;measurements:Record<string,string|number>;evaluator_name:string;workout_plan:string|null;workout_plan_name:string};
type Workout={id:string;name:string;status_label:string;review_date:string|null};
const field="h-10 rounded-xl border border-[var(--cfit-border)] bg-[var(--cfit-surface-elevated)] px-3 text-sm";
const today=()=>new Date().toISOString().slice(0,10);

export default function StudentAssessments({studentId}:{studentId:string}){
    const[items,setItems]=useState<Assessment[]>([]),[workouts,setWorkouts]=useState<Workout[]>([]),[change,setChange]=useState<{weight_kg:number;body_fat_percentage:number}|null>(null);
    const[loading,setLoading]=useState(true),[error,setError]=useState(false),[open,setOpen]=useState(false),[saving,setSaving]=useState(false);
    const[form,setForm]=useState({assessed_at:today(),next_assessment_at:"",weight_kg:"",height_cm:"",body_fat_percentage:"",blood_pressure:"",resting_heart_rate:"",goal:"",notes:"",waist:"",chest:"",hip:"",workout_plan:""});
    const load=useCallback(async()=>{try{setLoading(true);setError(false);const[a,w]=await Promise.all([Api.get("/operations/assessments/comparison/",{params:{student:studentId}}),Api.get("/workouts/plans/",{params:{student:studentId}})]);setItems(a.data.history);setChange(a.data.change);setWorkouts(w.data.results??w.data);}catch{setError(true);}finally{setLoading(false);}},[studentId]);
    useEffect(()=>{void load();},[load]);
    async function save(e:FormEvent){e.preventDefault();try{setSaving(true);await Api.post("/operations/assessments/",{student:studentId,assessed_at:form.assessed_at,next_assessment_at:form.next_assessment_at||null,weight_kg:form.weight_kg||null,height_cm:form.height_cm||null,body_fat_percentage:form.body_fat_percentage||null,blood_pressure:form.blood_pressure,resting_heart_rate:form.resting_heart_rate||null,goal:form.goal,notes:form.notes,workout_plan:form.workout_plan||null,measurements:{waist_cm:form.waist||null,chest_cm:form.chest||null,hip_cm:form.hip||null}});toast.success("Avaliação física registrada.");setOpen(false);setForm({...form,assessed_at:today(),weight_kg:"",body_fat_percentage:"",notes:""});await load();}catch{toast.error("Não foi possível registrar a avaliação. Confira os campos e sua permissão.");}finally{setSaving(false);}}
    const chart=useMemo(()=>{const valid=items.filter(x=>x.weight_kg).slice(-8);const values=valid.map(x=>Number(x.weight_kg));const min=Math.min(...values,0),max=Math.max(...values,1);return valid.map((x,i)=>({x:valid.length===1?50:8+i*84/(valid.length-1),y:88-(Number(x.weight_kg)-min)*72/(max-min||1),label:`${x.assessed_at}: ${x.weight_kg} kg`}));},[items]);
    if(loading)return <LoadingState label="Carregando avaliações..."/>;if(error)return <ErrorState onRetry={load}/>;
    return <section className="rounded-2xl border border-[var(--cfit-border)] bg-[var(--cfit-surface-primary)] p-6"><div className="flex flex-wrap items-center justify-between gap-3"><div className="flex items-center gap-3"><Scale className="text-blue-600"/><div><h2 className="font-black">Evolução física</h2><p className="text-sm text-[var(--cfit-text-secondary)]">Avaliações, comparação temporal e revisão do treino.</p></div></div><button className="cfit-primary-button" onClick={()=>setOpen(true)}><Plus size={16}/>Nova avaliação</button></div>
        {!items.length?<div className="mt-5"><EmptyState label="Nenhuma avaliação física" detail="Registre a primeira avaliação diretamente na ficha do aluno."/></div>:<><div className="mt-5 grid gap-3 sm:grid-cols-2">{change&&<><div className="rounded-xl bg-[var(--cfit-surface-elevated)] p-4 text-sm">Variação de peso <strong className="float-right">{change.weight_kg>0?"+":""}{change.weight_kg.toFixed(2)} kg</strong></div><div className="rounded-xl bg-[var(--cfit-surface-elevated)] p-4 text-sm">Variação de gordura <strong className="float-right">{change.body_fat_percentage>0?"+":""}{change.body_fat_percentage.toFixed(2)} p.p.</strong></div></>}</div>
        {chart.length>1&&<figure className="mt-5 rounded-xl border border-[var(--cfit-border)] p-4"><figcaption className="text-sm font-bold">Evolução do peso</figcaption><svg viewBox="0 0 100 100" role="img" aria-label={`Evolução do peso: ${chart.map(x=>x.label).join(", ")}`} className="mt-2 h-36 w-full overflow-visible"><polyline points={chart.map(x=>`${x.x},${x.y}`).join(" ")} fill="none" stroke="var(--cfit-action-primary)" strokeWidth="2"/>{chart.map(x=><circle key={x.label} cx={x.x} cy={x.y} r="2.5" fill="var(--cfit-action-primary)"><title>{x.label}</title></circle>)}</svg><p className="sr-only">{chart.map(x=>x.label).join("; ")}</p></figure>}
        <div className="mt-5 space-y-4">{[...items].reverse().map(item=><article key={item.id} className="rounded-xl border border-[var(--cfit-border)] p-4"><div className="flex flex-wrap justify-between gap-2 text-sm"><strong>{new Date(`${item.assessed_at}T12:00:00`).toLocaleDateString("pt-BR")}</strong><span className="text-[var(--cfit-text-secondary)]">{item.evaluator_name}</span></div><p className="mt-3 text-sm text-[var(--cfit-text-secondary)]">{item.weight_kg||"—"} kg · {item.height_cm||"—"} cm · {item.body_fat_percentage||"—"}% gordura · {item.blood_pressure||"pressão não informada"} · {item.resting_heart_rate||"—"} bpm</p><p className="mt-1 text-xs text-[var(--cfit-text-tertiary)]">Objetivo: {item.goal||"não informado"}{item.next_assessment_at?` · Próxima: ${new Date(`${item.next_assessment_at}T12:00:00`).toLocaleDateString("pt-BR")}`:""}</p>{item.workout_plan_name&&<p className="mt-2 text-xs font-bold text-blue-600">Revisão vinculada ao treino: {item.workout_plan_name}</p>}{item.notes&&<p className="mt-2 text-sm">{item.notes}</p>}</article>)}</div></>}
        <Modal open={open} title="Nova avaliação física" onClose={()=>setOpen(false)}><form onSubmit={save} className="grid gap-3 sm:grid-cols-2"><label className="text-xs font-bold">Data da avaliação<input required type="date" value={form.assessed_at} onChange={e=>setForm({...form,assessed_at:e.target.value})} className={`${field} mt-1 w-full`}/></label><label className="text-xs font-bold">Próxima avaliação<input type="date" value={form.next_assessment_at} onChange={e=>setForm({...form,next_assessment_at:e.target.value})} className={`${field} mt-1 w-full`}/></label><input type="number" step="0.01" min="1" placeholder="Peso (kg)" value={form.weight_kg} onChange={e=>setForm({...form,weight_kg:e.target.value})} className={field}/><input type="number" step="0.01" min="1" placeholder="Altura (cm)" value={form.height_cm} onChange={e=>setForm({...form,height_cm:e.target.value})} className={field}/><input type="number" step="0.01" min="0" max="100" placeholder="Gordura corporal (%)" value={form.body_fat_percentage} onChange={e=>setForm({...form,body_fat_percentage:e.target.value})} className={field}/><input placeholder="Pressão (ex.: 120/80)" pattern="[0-9]{2,3}/[0-9]{2,3}" value={form.blood_pressure} onChange={e=>setForm({...form,blood_pressure:e.target.value})} className={field}/><input type="number" min="20" max="250" placeholder="Frequência em repouso (bpm)" value={form.resting_heart_rate} onChange={e=>setForm({...form,resting_heart_rate:e.target.value})} className={field}/><input placeholder="Objetivo" maxLength={160} value={form.goal} onChange={e=>setForm({...form,goal:e.target.value})} className={field}/><input type="number" step="0.1" min="0" placeholder="Cintura (cm)" value={form.waist} onChange={e=>setForm({...form,waist:e.target.value})} className={field}/><input type="number" step="0.1" min="0" placeholder="Tórax (cm)" value={form.chest} onChange={e=>setForm({...form,chest:e.target.value})} className={field}/><input type="number" step="0.1" min="0" placeholder="Quadril (cm)" value={form.hip} onChange={e=>setForm({...form,hip:e.target.value})} className={field}/><select value={form.workout_plan} onChange={e=>setForm({...form,workout_plan:e.target.value})} className={field}><option value="">Sem treino vinculado</option>{workouts.map(x=><option key={x.id} value={x.id}>{x.name} · {x.status_label}</option>)}</select><textarea placeholder="Observações clínicas e operacionais" value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})} className="min-h-24 rounded-xl border border-[var(--cfit-border)] bg-[var(--cfit-surface-elevated)] p-3 text-sm sm:col-span-2"/><button disabled={saving} className="cfit-primary-button sm:col-span-2">{saving?"Salvando...":"Registrar avaliação"}</button></form></Modal>
    </section>;
}
